name: Auto Assign and Comment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Auto-assign issue or PR
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_GITHUB_TOKEN }}
          assignees: "winbo-yml-exe"
          numOfAssignee: 1

      - name: Add a comment to the issue
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello and thank you for your bug report! Someone should respond to your bug report within an hour. If the bug report is something critical, like ROMs not booting, please contact the owner at winbo.yml@proton.me. You can also contact him at Telegram (@winbo_yml) and Discord (winbo_the_dev).

      - name: Add a comment for pull request
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Sorry, but we don't accept pull requests."

      - name: Close pull request
        if: github.event_name == 'pull_request'
        run: |
          gh pr close ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
