name: Auto Assign and Comment

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign-comment:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: winbo-yml-exe
          numOfAssignee: 1

      - name: Add a comment to the issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            Hello and thank you for your bug report! Someone should respond to your bug report within an hour. If the bug report is something critical, like ROMs not booting, please contact the owner at winbo.yml@proton.me. You can also contact him at Telegram (@winbo_yml) and Discord (winbo_the_dev).
